kind: Service
apiVersion: v1
metadata:
  name: train-schedule-service
spec:
  type: NodePort
  selector:
    app: train-schedule
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 8080
    
    
---

apiVersion: extension/v1beta1
kind: Deployment
metadata:
  name: tain-schedule-deployement
  labels:
    app: train-schedule
spec:
  replicas: 4
  selector:
    matchLabels:
      app: train-schedule
  template:
    metadata:
      labels:
        app: train-schedule
    spec:
      containers:
      - name: train-schedule
        image: $DOCKER_IMAGE:$BUILD_NUMBER
        ports:
        - containerPort: 8080
